/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/pcaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload and ingest a PCAP/PCAPNG capture file with streaming SHA-256 hashing
         * @description Stream multipart upload directly to storage, compute SHA-256 in chunks, validate magic bytes.
         */
        post: operations["upload_pcap_api_v1_pcaps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pcaps/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate presigned S3 PUT URL for direct uploads exceeding 2 GiB
         * @description Generate time-limited presigned PUT URL allowing client to upload directly to MinIO/S3.
         */
        post: operations["get_presigned_upload_url_api_v1_pcaps_presign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve real-time execution progress, stage, and completion state
         * @description Query current pipeline execution state, stage details, packet counts, and ETA.
         */
        get: operations["get_task_status_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        /**
         * Revoke and cancel an ongoing analysis task
         * @description Terminate and revoke an active analysis task.
         */
        delete: operations["revoke_task_api_v1_tasks__task_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream full forensic analysis document incrementally without large RAM buffers
         * @description Stream full JSON document chunk by chunk using incremental generator.
         */
        get: operations["get_analysis_document_api_v1_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-side cursor-based session filtering and sorting (sub-200ms p95 on 100k flows)
         * @description Cursor-paginated session search with indexed filtering.
         */
        get: operations["list_analysis_sessions_api_v1_analyses__analysis_id__sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/verdict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit analyst forensic verdict and ground-truth label for a session
         * @description Record an analyst ground-truth verdict with forensic notes and confidence score.
         */
        post: operations["submit_session_verdict_api_v1_sessions__session_id__verdict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve forensic security audit log entries (admin role required)
         * @description Retrieve immutable audit event logs.
         */
        get: operations["list_audit_logs_api_v1_audit_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Version */
        get: operations["get_version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuditLogEntrySchema
         * @description Security audit event log entry.
         */
        AuditLogEntrySchema: {
            /** Id */
            id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Principal */
            principal: string;
            /** Role */
            role: string;
            /** Action */
            action: string;
            /** Resource Id */
            resource_id: string;
            /** Ip Address */
            ip_address?: string | null;
            /**
             * Status Code
             * @default 200
             */
            status_code: number;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /** Body_upload_pcap_api_v1_pcaps_post */
        Body_upload_pcap_api_v1_pcaps_post: {
            /**
             * File
             * @description PCAP or PCAPNG network capture file
             */
            file: string;
        };
        /**
         * CursorPaginatedSessions
         * @description Cursor-based server-side pagination response.
         */
        CursorPaginatedSessions: {
            /**
             * Items
             * @description Page session records.
             */
            items: components["schemas"]["SessionSummarySchema"][];
            /**
             * Next Cursor
             * @description Opaque cursor string for fetching the next page.
             */
            next_cursor?: string | null;
            /**
             * Has More
             * @description Whether additional records exist beyond this page.
             */
            has_more: boolean;
            /**
             * Total Count
             * @description Total matched sessions across all pages.
             */
            total_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PcapUploadResponse
         * @description HTTP 202 / 200 Upload ingestion response.
         */
        PcapUploadResponse: {
            /**
             * Analysis Id
             * @description Unique UUID for this analysis execution.
             */
            analysis_id: string;
            /**
             * Task Id
             * @description Celery asynchronous pipeline task identifier.
             */
            task_id: string;
            /**
             * Sha256
             * @description Hexadecimal SHA-256 digest of uploaded PCAP artifact.
             */
            sha256: string;
            /**
             * Status Url
             * @description Polling endpoint for progress and state updates.
             */
            status_url: string;
            /**
             * Duplicate Of
             * @description If hash already exists in repository, ID of existing analysis.
             */
            duplicate_of?: string | null;
            /**
             * Is Duplicate
             * @description Whether this upload was deduplicated against an existing archive.
             * @default false
             */
            is_duplicate: boolean;
        };
        /**
         * PresignedUploadRequest
         * @description Request for direct-to-object-storage upload for large capture files.
         */
        PresignedUploadRequest: {
            /**
             * Filename
             * @description Target PCAP/PCAPNG capture filename.
             */
            filename: string;
            /**
             * Size Bytes
             * @description Exact file size in bytes.
             */
            size_bytes: number;
            /**
             * Sha256
             * @description Optional anticipated SHA-256 checksum.
             */
            sha256?: string | null;
        };
        /**
         * PresignedUploadResponse
         * @description Presigned PUT URL for direct MinIO/S3 ingestion.
         */
        PresignedUploadResponse: {
            /**
             * Upload Url
             * @description Time-limited presigned S3 PUT URL.
             */
            upload_url: string;
            /**
             * File Key
             * @description Assigned storage key in object bucket.
             */
            file_key: string;
            /**
             * Expires In Seconds
             * @description Validity period of presigned URL.
             * @default 3600
             */
            expires_in_seconds: number;
            /**
             * Analysis Id
             * @description Pre-allocated analysis identifier.
             */
            analysis_id: string;
        };
        /**
         * SessionSummarySchema
         * @description Summary record for session listing and cursor pagination.
         */
        SessionSummarySchema: {
            /**
             * Id
             * @description Unique session identifier.
             */
            id: string;
            /**
             * Analysis Id
             * @description Parent analysis execution ID.
             */
            analysis_id: string;
            /**
             * Client Ip
             * @description Client IP address.
             */
            client_ip: string;
            /**
             * Client Port
             * @description Client TCP port.
             */
            client_port: number;
            /**
             * Server Ip
             * @description Server IP address.
             */
            server_ip: string;
            /**
             * Server Port
             * @description Server TCP port.
             */
            server_port: number;
            /**
             * Protocol
             * @description SMTP, IMAP, or POP3.
             */
            protocol: string;
            /**
             * Mode
             * @description EXPLICIT or IMPLICIT.
             */
            mode: string;
            /**
             * Starttls State
             * @description Final STARTTLS state (S0-S4).
             */
            starttls_state: string;
            /**
             * Risk Score
             * @description NIST SP 800-57 risk score (0-100).
             */
            risk_score: number;
            /**
             * Risk Band
             * @description SECURE, ACCEPTABLE, WEAK, HIGH, CRITICAL.
             */
            risk_band: string;
            /**
             * Ja3
             * @description Client JA3 fingerprint hash.
             */
            ja3?: string | null;
            /**
             * Ja4
             * @description Client JA4 fingerprint.
             */
            ja4?: string | null;
            /**
             * Sni
             * @description SNI server hostname.
             */
            sni?: string | null;
            /**
             * First Seen
             * @description First packet capture timestamp (epoch).
             */
            first_seen: number;
            /**
             * Duration Sec
             * @description TCP session duration in seconds.
             */
            duration_sec: number;
            /**
             * Is Anomaly
             * @description ML anomaly flag.
             * @default false
             */
            is_anomaly: boolean;
        };
        /**
         * TaskStatusResponse
         * @description Real-time task tracking status payload.
         */
        TaskStatusResponse: {
            /**
             * Task Id
             * @description Celery task identifier.
             */
            task_id: string;
            /**
             * State
             * @description Current pipeline execution state.
             * @enum {string}
             */
            state: "PENDING" | "PARSING" | "SCORING" | "SCORING_ML" | "SUCCESS" | "FAILURE" | "REVOKED";
            /**
             * Progress
             * @description Normalized progress fraction 0.0 to 1.0.
             * @default 0
             */
            progress: number;
            /**
             * Stage Detail
             * @description Human-readable description of active pipeline stage.
             * @default
             */
            stage_detail: string;
            /**
             * Packets Processed
             * @description Number of packets parsed so far.
             * @default 0
             */
            packets_processed: number;
            /**
             * Total Packets
             * @description Total packet count if known.
             */
            total_packets?: number | null;
            /**
             * Eta Seconds
             * @description Estimated time remaining in seconds.
             */
            eta_seconds?: number | null;
            /**
             * Error
             * @description Error message if state is FAILURE.
             */
            error?: string | null;
            /**
             * Analysis Id
             * @description Resulting analysis ID upon completion.
             */
            analysis_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerdictSubmissionRequest
         * @description Analyst verdict and forensic ground-truth submission.
         */
        VerdictSubmissionRequest: {
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "BENIGN" | "SUSPICIOUS" | "MALICIOUS" | "POLICY_VIOLATION";
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Tags */
            tags?: string[];
        };
        /**
         * VerdictSubmissionResponse
         * @description Verdict confirmation payload.
         */
        VerdictSubmissionResponse: {
            /** Verdict Id */
            verdict_id: string;
            /** Session Id */
            session_id: string;
            /** Analyst Id */
            analyst_id: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at?: string;
            /** Verdict */
            verdict: string;
            /**
             * Status
             * @default RECORDED
             */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_pcap_api_v1_pcaps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_pcap_api_v1_pcaps_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PcapUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_presigned_upload_url_api_v1_pcaps_presign_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignedUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_status_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_task_api_v1_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_document_api_v1_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_analysis_sessions_api_v1_analyses__analysis_id__sessions_get: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor token */
                cursor?: string | null;
                /** @description Page item limit */
                limit?: number;
                /** @description Minimum risk score filter */
                min_risk?: number | null;
                /** @description Risk band filter: SECURE, ACCEPTABLE, WEAK, HIGH, CRITICAL */
                band?: string | null;
                /** @description Mail protocol: SMTP, IMAP, POP3 */
                protocol?: string | null;
                /** @description STARTTLS state: S0_TCP_EST to S4_TLS_READY */
                starttls_state?: string | null;
                /** @description ML anomaly flag filter */
                is_anomaly?: boolean | null;
                /** @description Client JA3 hash filter */
                ja3?: string | null;
                /** @description Target SNI hostname substring */
                sni?: string | null;
                /** @description Destination server IP address */
                dst_ip?: string | null;
                /** @description Sort field: risk, anomaly, ts */
                sort_by?: string;
                /** @description Sort order: asc or desc */
                sort_order?: string;
            };
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPaginatedSessions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_session_verdict_api_v1_sessions__session_id__verdict_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerdictSubmissionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerdictSubmissionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_logs_api_v1_audit_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogEntrySchema"][];
                };
            };
        };
    };
    health_check_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
