"""Generate static IANA TLS cipher suite database (data/ciphers.json).

Includes official IANA TLS registry definitions plus hand-curated SSLv2/SSLv3,
export, NULL, RC4, DES/3DES, and proprietary cipher suites with deterministic
NIST SP 800-52r2 cryptographic posture classifications.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

CURATED_CIPHERS: list[dict[str, Any]] = [
    # TLS 1.3 suites (RFC 8446)
    {
        "id": "0x1301",
        "name": "TLS_AES_128_GCM_SHA256",
        "kex": "ECDHE",
        "auth": "any",
        "enc": "AES-128-GCM",
        "enc_bits": 128,
        "mac": "AEAD",
        "hash": "SHA256",
        "pfs": True,
        "aead": True,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "approved",
    },
    {
        "id": "0x1302",
        "name": "TLS_AES_256_GCM_SHA384",
        "kex": "ECDHE",
        "auth": "any",
        "enc": "AES-256-GCM",
        "enc_bits": 256,
        "mac": "AEAD",
        "hash": "SHA384",
        "pfs": True,
        "aead": True,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "approved",
    },
    {
        "id": "0x1303",
        "name": "TLS_CHACHA20_POLY1305_SHA256",
        "kex": "ECDHE",
        "auth": "any",
        "enc": "CHACHA20-POLY1305",
        "enc_bits": 256,
        "mac": "AEAD",
        "hash": "SHA256",
        "pfs": True,
        "aead": True,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "approved",
    },
    {
        "id": "0x1304",
        "name": "TLS_AES_128_CCM_SHA256",
        "kex": "ECDHE",
        "auth": "any",
        "enc": "AES-128-CCM",
        "enc_bits": 128,
        "mac": "AEAD",
        "hash": "SHA256",
        "pfs": True,
        "aead": True,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "approved",
    },
    {
        "id": "0x1305",
        "name": "TLS_AES_128_CCM_8_SHA256",
        "kex": "ECDHE",
        "auth": "any",
        "enc": "AES-128-CCM-8",
        "enc_bits": 128,
        "mac": "AEAD",
        "hash": "SHA256",
        "pfs": True,
        "aead": True,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "approved",
    },
    # Modern TLS 1.2 ECDHE AEAD Suites (NIST Approved)
    {
        "id": "0xC02B",
        "name": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "kex": "ECDHE",
        "auth": "ECDSA",
        "enc": "AES-128-GCM",
        "enc_bits": 128,
        "mac": "AEAD",
        "hash": "SHA256",
        "pfs": True,
        "aead": True,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "approved",
    },
    {
        "id": "0xC02C",
        "name": "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "kex": "ECDHE",
        "auth": "ECDSA",
        "enc": "AES-256-GCM",
        "enc_bits": 256,
        "mac": "AEAD",
        "hash": "SHA384",
        "pfs": True,
        "aead": True,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "approved",
    },
    {
        "id": "0xC02F",
        "name": "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "kex": "ECDHE",
        "auth": "RSA",
        "enc": "AES-128-GCM",
        "enc_bits": 128,
        "mac": "AEAD",
        "hash": "SHA256",
        "pfs": True,
        "aead": True,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "approved",
    },
    {
        "id": "0xC030",
        "name": "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "kex": "ECDHE",
        "auth": "RSA",
        "enc": "AES-256-GCM",
        "enc_bits": 256,
        "mac": "AEAD",
        "hash": "SHA384",
        "pfs": True,
        "aead": True,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "approved",
    },
    {
        "id": "0xCCA8",
        "name": "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
        "kex": "ECDHE",
        "auth": "RSA",
        "enc": "CHACHA20-POLY1305",
        "enc_bits": 256,
        "mac": "AEAD",
        "hash": "SHA256",
        "pfs": True,
        "aead": True,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "approved",
    },
    {
        "id": "0xCCA9",
        "name": "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
        "kex": "ECDHE",
        "auth": "ECDSA",
        "enc": "CHACHA20-POLY1305",
        "enc_bits": 256,
        "mac": "AEAD",
        "hash": "SHA256",
        "pfs": True,
        "aead": True,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "approved",
    },
    {
        "id": "0x009E",
        "name": "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256",
        "kex": "DHE",
        "auth": "RSA",
        "enc": "AES-128-GCM",
        "enc_bits": 128,
        "mac": "AEAD",
        "hash": "SHA256",
        "pfs": True,
        "aead": True,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "approved",
    },
    {
        "id": "0x009F",
        "name": "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384",
        "kex": "DHE",
        "auth": "RSA",
        "enc": "AES-256-GCM",
        "enc_bits": 256,
        "mac": "AEAD",
        "hash": "SHA384",
        "pfs": True,
        "aead": True,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "approved",
    },
    # TLS 1.2 CBC Suites (NIST Legacy)
    {
        "id": "0xC027",
        "name": "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
        "kex": "ECDHE",
        "auth": "RSA",
        "enc": "AES-128-CBC",
        "enc_bits": 128,
        "mac": "HMAC-SHA256",
        "hash": "SHA256",
        "pfs": True,
        "aead": False,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "legacy",
    },
    {
        "id": "0xC028",
        "name": "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384",
        "kex": "ECDHE",
        "auth": "RSA",
        "enc": "AES-256-CBC",
        "enc_bits": 256,
        "mac": "HMAC-SHA384",
        "hash": "SHA384",
        "pfs": True,
        "aead": False,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "legacy",
    },
    {
        "id": "0xC013",
        "name": "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
        "kex": "ECDHE",
        "auth": "RSA",
        "enc": "AES-128-CBC",
        "enc_bits": 128,
        "mac": "HMAC-SHA1",
        "hash": "SHA1",
        "pfs": True,
        "aead": False,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "legacy",
    },
    {
        "id": "0xC014",
        "name": "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
        "kex": "ECDHE",
        "auth": "RSA",
        "enc": "AES-256-CBC",
        "enc_bits": 256,
        "mac": "HMAC-SHA1",
        "hash": "SHA1",
        "pfs": True,
        "aead": False,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "legacy",
    },
    {
        "id": "0x002F",
        "name": "TLS_RSA_WITH_AES_128_CBC_SHA",
        "kex": "RSA",
        "auth": "RSA",
        "enc": "AES-128-CBC",
        "enc_bits": 128,
        "mac": "HMAC-SHA1",
        "hash": "SHA1",
        "pfs": False,
        "aead": False,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "legacy",
    },
    {
        "id": "0x0035",
        "name": "TLS_RSA_WITH_AES_256_CBC_SHA",
        "kex": "RSA",
        "auth": "RSA",
        "enc": "AES-256-CBC",
        "enc_bits": 256,
        "mac": "HMAC-SHA1",
        "hash": "SHA1",
        "pfs": False,
        "aead": False,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "legacy",
    },
    {
        "id": "0x003C",
        "name": "TLS_RSA_WITH_AES_128_CBC_SHA256",
        "kex": "RSA",
        "auth": "RSA",
        "enc": "AES-128-CBC",
        "enc_bits": 128,
        "mac": "HMAC-SHA256",
        "hash": "SHA256",
        "pfs": False,
        "aead": False,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "legacy",
    },
    {
        "id": "0x003D",
        "name": "TLS_RSA_WITH_AES_256_CBC_SHA256",
        "kex": "RSA",
        "auth": "RSA",
        "enc": "AES-256-CBC",
        "enc_bits": 256,
        "mac": "HMAC-SHA256",
        "hash": "SHA256",
        "pfs": False,
        "aead": False,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "legacy",
    },
    # Obsolete & Broken Suites (3DES, RC4, DES, EXPORT, NULL, Anon DH) -> Prohibited
    {
        "id": "0x000A",
        "name": "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
        "kex": "RSA",
        "auth": "RSA",
        "enc": "3DES-EDE-CBC",
        "enc_bits": 112,
        "mac": "HMAC-SHA1",
        "hash": "SHA1",
        "pfs": False,
        "aead": False,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "prohibited",
    },
    {
        "id": "0xC012",
        "name": "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA",
        "kex": "ECDHE",
        "auth": "RSA",
        "enc": "3DES-EDE-CBC",
        "enc_bits": 112,
        "mac": "HMAC-SHA1",
        "hash": "SHA1",
        "pfs": True,
        "aead": False,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "prohibited",
    },
    {
        "id": "0x0004",
        "name": "TLS_RSA_WITH_RC4_128_MD5",
        "kex": "RSA",
        "auth": "RSA",
        "enc": "RC4-128",
        "enc_bits": 128,
        "mac": "HMAC-MD5",
        "hash": "MD5",
        "pfs": False,
        "aead": False,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "prohibited",
    },
    {
        "id": "0x0005",
        "name": "TLS_RSA_WITH_RC4_128_SHA",
        "kex": "RSA",
        "auth": "RSA",
        "enc": "RC4-128",
        "enc_bits": 128,
        "mac": "HMAC-SHA1",
        "hash": "SHA1",
        "pfs": False,
        "aead": False,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "prohibited",
    },
    {
        "id": "0xC007",
        "name": "TLS_ECDHE_ECDSA_WITH_RC4_128_SHA",
        "kex": "ECDHE",
        "auth": "ECDSA",
        "enc": "RC4-128",
        "enc_bits": 128,
        "mac": "HMAC-SHA1",
        "hash": "SHA1",
        "pfs": True,
        "aead": False,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "prohibited",
    },
    {
        "id": "0xC011",
        "name": "TLS_ECDHE_RSA_WITH_RC4_128_SHA",
        "kex": "ECDHE",
        "auth": "RSA",
        "enc": "RC4-128",
        "enc_bits": 128,
        "mac": "HMAC-SHA1",
        "hash": "SHA1",
        "pfs": True,
        "aead": False,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "prohibited",
    },
    {
        "id": "0x0009",
        "name": "TLS_RSA_WITH_DES_CBC_SHA",
        "kex": "RSA",
        "auth": "RSA",
        "enc": "DES-CBC",
        "enc_bits": 56,
        "mac": "HMAC-SHA1",
        "hash": "SHA1",
        "pfs": False,
        "aead": False,
        "export": False,
        "anon": False,
        "null_enc": False,
        "nist_status": "prohibited",
    },
    {
        "id": "0x0003",
        "name": "TLS_RSA_EXPORT_WITH_RC4_40_MD5",
        "kex": "RSA",
        "auth": "RSA",
        "enc": "RC4-40",
        "enc_bits": 40,
        "mac": "HMAC-MD5",
        "hash": "MD5",
        "pfs": False,
        "aead": False,
        "export": True,
        "anon": False,
        "null_enc": False,
        "nist_status": "prohibited",
    },
    {
        "id": "0x0006",
        "name": "TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5",
        "kex": "RSA",
        "auth": "RSA",
        "enc": "RC2-CBC-40",
        "enc_bits": 40,
        "mac": "HMAC-MD5",
        "hash": "MD5",
        "pfs": False,
        "aead": False,
        "export": True,
        "anon": False,
        "null_enc": False,
        "nist_status": "prohibited",
    },
    {
        "id": "0x0008",
        "name": "TLS_RSA_EXPORT_WITH_DES40_CBC_SHA",
        "kex": "RSA",
        "auth": "RSA",
        "enc": "DES40-CBC",
        "enc_bits": 40,
        "mac": "HMAC-SHA1",
        "hash": "SHA1",
        "pfs": False,
        "aead": False,
        "export": True,
        "anon": False,
        "null_enc": False,
        "nist_status": "prohibited",
    },
    {
        "id": "0x0001",
        "name": "TLS_RSA_WITH_NULL_MD5",
        "kex": "RSA",
        "auth": "RSA",
        "enc": "NULL",
        "enc_bits": 0,
        "mac": "HMAC-MD5",
        "hash": "MD5",
        "pfs": False,
        "aead": False,
        "export": False,
        "anon": False,
        "null_enc": True,
        "nist_status": "prohibited",
    },
    {
        "id": "0x0002",
        "name": "TLS_RSA_WITH_NULL_SHA",
        "kex": "RSA",
        "auth": "RSA",
        "enc": "NULL",
        "enc_bits": 0,
        "mac": "HMAC-SHA1",
        "hash": "SHA1",
        "pfs": False,
        "aead": False,
        "export": False,
        "anon": False,
        "null_enc": True,
        "nist_status": "prohibited",
    },
    {
        "id": "0x0018",
        "name": "TLS_DH_anon_WITH_RC4_128_MD5",
        "kex": "DH_anon",
        "auth": "anon",
        "enc": "RC4-128",
        "enc_bits": 128,
        "mac": "HMAC-MD5",
        "hash": "MD5",
        "pfs": True,
        "aead": False,
        "export": False,
        "anon": True,
        "null_enc": False,
        "nist_status": "prohibited",
    },
    {
        "id": "0x001B",
        "name": "TLS_DH_anon_WITH_3DES_EDE_CBC_SHA",
        "kex": "DH_anon",
        "auth": "anon",
        "enc": "3DES-EDE-CBC",
        "enc_bits": 112,
        "mac": "HMAC-SHA1",
        "hash": "SHA1",
        "pfs": True,
        "aead": False,
        "export": False,
        "anon": True,
        "null_enc": False,
        "nist_status": "prohibited",
    },
]


def generate_ciphers_json(target_path: Path) -> None:
    """Generate normalized dictionary keyed by hex string."""
    ciphers_map: dict[str, dict[str, Any]] = {}

    for entry in CURATED_CIPHERS:
        raw_id = entry["id"].upper()
        # Normalize key e.g. "0x1301" -> "0x1301"
        ciphers_map[raw_id.lower()] = entry
        ciphers_map[raw_id] = entry

    target_path.parent.mkdir(parents=True, exist_ok=True)
    with open(target_path, "w", encoding="utf-8") as f:
        json.dump(ciphers_map, f, indent=2, sort_keys=True)


if __name__ == "__main__":
    out_file = Path(__file__).resolve().parent.parent / "data" / "ciphers.json"
    generate_ciphers_json(out_file)
    print(f"Generated {out_file} with {len(CURATED_CIPHERS)} cipher suites.")
